Repository element-hq/matrix-react-sdk, pull requests merged in 2024-09, with the labels that each got.

#3 Update codeowners to element-hq teams
  .github/CODEOWNERS
Labels: T-Task

#11 Update GH org in the sonar config file
  sonar-project.properties
Labels: T-Task

#10 Update repos for changelog fetching
  src/components/views/dialogs/ChangelogDialog.tsx
  test/components/views/dialogs/ChangelogDialog-test.tsx
  test/components/views/dialogs/__snapshots__/ChangelogDialog-test.tsx.snap
Labels: T-Task

#7 Change org to element-hq
  package.json
Labels: T-Task

#17 Fix flacky test of pinned messages
  playwright/e2e/pinned-messages/pinned-messages.spec.ts
  playwright/snapshots/pinned-messages/pinned-messages.spec.ts/pinned-message-banner-2-linux.png
  playwright/snapshots/pinned-messages/pinned-messages.spec.ts/pinned-messages-list-pin-3-linux.png
  playwright/snapshots/pinned-messages/pinned-messages.spec.ts/pinned-messages-list-unpin-2-linux.png
Labels: T-Task

#23 Remove release announcement of the new header
  src/components/views/rooms/RoomHeader.tsx
  src/i18n/strings/en_EN.json
  src/stores/ReleaseAnnouncementStore.ts
  test/components/structures/__snapshots__/RoomView-test.tsx.snap
  test/components/views/rooms/__snapshots__/RoomHeader-test.tsx.snap
  test/stores/ReleaseAnnouncementStore-test.tsx
Labels: T-Enhancement

#25 Enable message pinning labs by default
  playwright/e2e/pinned-messages/pinned-messages.spec.ts
  playwright/snapshots/crypto/crypto.spec.ts/RoomSummaryCard-with-verified-e2ee-linux.png
  playwright/snapshots/polls/polls.spec.ts/Polls-Timeline-tile-no-votes-linux.png
  playwright/snapshots/right-panel/right-panel.spec.ts/with-name-and-address-linux.png
  playwright/snapshots/threads/threads.spec.ts/Reply-to-the-location-on-ThreadView-linux.png
  src/settings/Settings.tsx
  test/test-utils/test-utils.ts
Labels: T-Enhancement

#21 Add labels file
  .github/labels.yml
  .github/workflows/sync-labels.yml
Labels: T-Task

#27 Log clearer errors when picklekey goes missing
  src/Lifecycle.ts
  src/components/structures/MatrixChat.tsx
  src/utils/tokens/tokens.ts
  test/Lifecycle-test.ts
Labels: T-Task

#28 Reduce pinned message banner size
  playwright/snapshots/pinned-messages/pinned-messages.spec.ts/pinned-message-banner-2-Msg1-linux.png
  playwright/snapshots/pinned-messages/pinned-messages.spec.ts/pinned-message-banner-2-Msg2-linux.png
  playwright/snapshots/pinned-messages/pinned-messages.spec.ts/pinned-message-banner-4-Msg1-linux.png
  playwright/snapshots/pinned-messages/pinned-messages.spec.ts/pinned-message-banner-4-Msg2-linux.png
  playwright/snapshots/pinned-messages/pinned-messages.spec.ts/pinned-message-banner-4-Msg3-linux.png
  playwright/snapshots/pinned-messages/pinned-messages.spec.ts/pinned-message-banner-4-Msg4-linux.png
  res/css/views/rooms/_PinnedMessageBanner.pcss
Labels: T-Enhancement

#29 Add config option to force verification
  src/IConfigOptions.ts
  src/components/structures/auth/CompleteSecurity.tsx
  test/components/structures/auth/CompleteSecurity-test.tsx
  test/test-utils/test-utils.ts
Labels: T-Enhancement

#37 Fix huge usage bandwidth and performance issue of pinned message banner.
  src/hooks/usePinnedEvents.ts
  src/utils/promise.ts
  test/components/views/right_panel/PinnedMessagesCard-test.tsx
  test/components/views/right_panel/__snapshots__/PinnedMessagesCard-test.tsx.snap
  test/utils/promise-test.ts
Labels: T-Defect

#32 update test to work with Rust crypto v8.0.0
  playwright/e2e/crypto/event-shields.spec.ts
Labels: T-Task

#34 Add support for `org.matrix.cross_signing_reset` UIA stage flow
  src/components/structures/InteractiveAuth.tsx
  src/components/views/auth/InteractiveAuthEntryComponents.tsx
  src/i18n/strings/en_EN.json
  test/components/views/auth/InteractiveAuthEntryComponents-test.tsx
  test/components/views/auth/__snapshots__/InteractiveAuthEntryComponents-test.tsx.snap
Labels: T-Enhancement

#40 Fix timeout type
  src/hooks/useUserTimezone.ts
Labels: T-Defect

#42 Add mobile registration
  res/css/_components.pcss
  res/css/structures/auth/_MobileRegistration.pcss
  src/components/structures/MatrixChat.tsx
  src/components/structures/auth/Registration.tsx
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
Labels: T-Enhancement

#47 Playwright test for E2E messages from deleted devices
  playwright/e2e/crypto/event-shields.spec.ts
Labels: T-Task

#46 Add Release announcement for the pinning message list
  src/components/views/right_panel/RoomSummaryCard.tsx
  src/i18n/strings/en_EN.json
  src/stores/ReleaseAnnouncementStore.ts
  test/components/views/right_panel/__snapshots__/RoomSummaryCard-test.tsx.snap
  test/stores/ReleaseAnnouncementStore-test.tsx
Labels: T-Enhancement

#56 Pass bot token through explicitly
  .github/workflows/release.yml
Labels: T-Task

#49 Playwright: factor out some common code
  playwright/pages/bot.ts
  playwright/pages/client.ts
Labels: T-Task

#60 Replace old reference of `matrix-org/matrix-react-sdk` by `element-hq/matrix-react-sdk` in CI
  .github/workflows/notify-element-web.yml
  .github/workflows/tests.yml
Labels: T-Task

#48 Ignore chat effect when older than 48h
  src/components/structures/RoomView.tsx
  src/components/views/elements/EffectsOverlay.tsx
  test/components/views/elements/EffectsOverlay-test.tsx
  test/components/views/elements/__snapshots__/EffectsOverlay-test.tsx.snap
Labels: T-Enhancement

#55 Update to use non deprecated methods to derive key from passphrase
  .eslintrc.js
  src/SecurityManager.ts
Labels: T-Task

#54 Update to use non deprecated methods to decode recovery key
  .eslintrc.js
  src/SecurityManager.ts
  src/components/views/dialogs/security/AccessSecretStorageDialog.tsx
  src/components/views/dialogs/security/RestoreKeyBackupDialog.tsx
  test/components/views/dialogs/AccessSecretStorageDialog-test.tsx
  test/components/views/dialogs/security/RestoreKeyBackupDialog-test.tsx
  test/components/views/dialogs/security/__snapshots__/RestoreKeyBackupDialog-test.tsx.snap
Labels: T-Task

#62 Mobile registration optimizations and tests
  src/components/structures/MatrixChat.tsx
  src/components/structures/auth/Registration.tsx
  src/components/views/auth/EmailField.tsx
  src/components/views/auth/PassphraseConfirmField.tsx
  src/components/views/auth/PassphraseField.tsx
  src/components/views/auth/RegistrationForm.tsx
  src/components/views/elements/Field.tsx
  test/components/structures/MatrixChat-test.tsx
  test/components/structures/auth/Registration-test.tsx
Labels: T-Enhancement

#81 Maybe fix flakey AddRemoveThreepid test
  test/components/views/settings/AddRemoveThreepids-test.tsx
Labels: T-Task

#82 Grant Element Call widget capabilities for "raise hand" feature
  src/stores/widgets/StopGapWidgetDriver.ts
  test/stores/widgets/StopGapWidgetDriver-test.ts
Labels: T-Enhancement

#86 Crypto: fix display of device key
  src/components/views/settings/CryptographyPanel.tsx
  test/components/views/settings/CryptographyPanel-test.tsx
  test/components/views/settings/tabs/user/__snapshots__/SecurityUserSettingsTab-test.tsx.snap
  test/test-utils/client.ts
  test/test-utils/test-utils.ts
Labels: T-Defect

#87 Fix accessible label on left panel spotlight trigger
  src/components/structures/RoomSearch.tsx
Labels: T-Defect

#41 Use `strong` over `b` for improved a11y semantics
  res/css/views/auth/_AuthBody.pcss
  src/IdentityAuthClient.tsx
  src/RoomInvite.tsx
  src/components/structures/auth/forgot-password/CheckEmail.tsx
  src/components/structures/auth/forgot-password/EnterEmail.tsx
  src/components/structures/auth/forgot-password/VerifyEmailModal.tsx
  src/components/views/auth/InteractiveAuthEntryComponents.tsx
  src/components/views/auth/LoginWithQRFlow.tsx
  src/components/views/dialogs/AnalyticsLearnMoreDialog.tsx
  src/components/views/dialogs/BugReportDialog.tsx
  src/components/views/dialogs/CreateRoomDialog.tsx
  src/components/views/dialogs/CreateSubspaceDialog.tsx
  src/components/views/dialogs/LeaveSpaceDialog.tsx
  src/components/views/dialogs/ManageRestrictedJoinRuleDialog.tsx
  src/components/views/dialogs/ManualDeviceKeyVerificationDialog.tsx
  src/components/views/dialogs/RegistrationEmailPromptDialog.tsx
  src/components/views/dialogs/RoomUpgradeWarningDialog.tsx
  src/components/views/dialogs/UploadFailureDialog.tsx
  src/components/views/dialogs/devtools/SettingExplorer.tsx
  src/components/views/dialogs/security/RestoreKeyBackupDialog.tsx
  src/components/views/rooms/NewRoomIntro.tsx
  src/components/views/rooms/RoomPreviewCard.tsx
  src/components/views/rooms/RoomSearchAuxPanel.tsx
  src/components/views/rooms/RoomUpgradeWarningBar.tsx
  src/components/views/settings/CryptographyPanel.tsx
  src/components/views/settings/JoinRuleSettings.tsx
  src/components/views/settings/SecureBackupPanel.tsx
  src/components/views/settings/SetIdServer.tsx
  src/components/views/settings/SetIntegrationManager.tsx
  src/components/views/settings/tabs/room/AdvancedRoomSettingsTab.tsx
  src/components/views/settings/tabs/room/SecurityRoomSettingsTab.tsx
  src/components/views/settings/tabs/user/HelpUserSettingsTab.tsx
  src/components/views/spaces/SpaceSettingsVisibilityTab.tsx
  src/utils/exportUtils/HtmlExport.tsx
  src/widgets/CapabilityText.tsx
  test/components/structures/__snapshots__/RoomView-test.tsx.snap
  test/components/views/auth/__snapshots__/InteractiveAuthEntryComponents-test.tsx.snap
  test/components/views/dialogs/__snapshots__/ManageRestrictedJoinRuleDialog-test.tsx.snap
  test/components/views/dialogs/__snapshots__/ManualDeviceKeyVerificationDialog-test.tsx.snap
  test/components/views/dialogs/security/__snapshots__/RestoreKeyBackupDialog-test.tsx.snap
  test/components/views/settings/CryptographyPanel-test.tsx
  test/components/views/settings/__snapshots__/SecureBackupPanel-test.tsx.snap
  test/components/views/settings/__snapshots__/SetIntegrationManager-test.tsx.snap
  test/components/views/settings/devices/__snapshots__/LoginWithQRFlow-test.tsx.snap
  test/components/views/settings/tabs/room/__snapshots__/SecurityRoomSettingsTab-test.tsx.snap
  test/components/views/settings/tabs/user/__snapshots__/SecurityUserSettingsTab-test.tsx.snap
  test/components/views/spaces/__snapshots__/SpaceSettingsVisibilityTab-test.tsx.snap
  test/utils/exportUtils/__snapshots__/HTMLExport-test.ts.snap
Labels: T-Enhancement

#88 Open room settings on room header avatar click
  playwright/e2e/room/room-header.spec.ts
  playwright/element-web-test.ts
  playwright/snapshots/editing/editing.spec.ts/message-edit-history-dialog-linux.png
  playwright/snapshots/room/room-header.spec.ts/room-header-long-name-linux.png
  playwright/snapshots/threads/threads.spec.ts/Reply-to-the-location-on-ThreadView-linux.png
  res/css/views/rooms/_RoomHeader.pcss
  src/components/views/avatars/BaseAvatar.tsx
  src/components/views/rooms/RoomHeader.tsx
  src/i18n/strings/en_EN.json
  test/components/structures/__snapshots__/RoomView-test.tsx.snap
  test/components/views/rooms/RoomHeader-test.tsx
  test/components/views/rooms/__snapshots__/RoomHeader-test.tsx.snap
Labels: T-Enhancement

#94 Pop right panel timeline when unmaximising widget to avoid double timeline
  src/components/views/elements/AppTile.tsx
Labels: T-Defect

#91 Improve contrast for timestamps, date separators & spotlight trigger
  playwright/snapshots/editing/editing.spec.ts/message-edit-history-dialog-linux.png
  playwright/snapshots/polls/polls.spec.ts/ThreadView-with-a-poll-on-bubble-layout-linux.png
  playwright/snapshots/polls/polls.spec.ts/ThreadView-with-a-poll-on-group-layout-linux.png
  playwright/snapshots/right-panel/file-panel.spec.ts/file-tiles-list-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/collapsed-gels-and-messages-irc-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/collapsed-gels-bubble-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/configured-room-irc-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/event-line-inline-start-margin-irc-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/expanded-gels-and-messages-irc-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/expanded-gels-irc-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/expanded-gels-modern-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/expanded-gels-redaction-placeholder-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/highlighted-search-results-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/long-strings-with-reply-bubble-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/long-strings-with-reply-irc-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/long-strings-with-reply-modern-layout-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/search-results-with-TextualEvent-linux.png
  res/css/structures/_RoomSearch.pcss
  res/css/views/messages/_TimelineSeparator.pcss
  res/themes/dark/css/_dark.pcss
  res/themes/light/css/_light.pcss
Labels: T-Enhancement

#92 Add labs option to exclude unverified devices
  src/MatrixClientPeg.ts
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
  src/settings/controllers/DeviceIsolationModeController.ts
  test/components/structures/MatrixChat-test.tsx
  test/settings/controllers/DeviceIsolationModeController-test.ts
  test/test-utils/test-utils.ts
Labels: T-Enhancement

#95 Allow joining calls and video rooms without enabling the labs flags
  src/Notifier.ts
  src/components/structures/RoomView.tsx
  src/components/views/context_menus/RoomContextMenu.tsx
  src/components/views/right_panel/RightPanelTabs.tsx
  src/components/views/right_panel/RoomSummaryCard.tsx
  src/components/views/rooms/LegacyRoomHeader.tsx
  src/components/views/rooms/RoomHeader.tsx
  src/components/views/rooms/RoomInfoLine.tsx
  src/components/views/rooms/RoomPreviewCard.tsx
  src/hooks/room/useRoomCall.ts
  src/i18n/strings/en_EN.json
  src/models/Call.ts
  src/utils/video-rooms.ts
  test/Notifier-test.ts
  test/components/structures/MatrixChat-test.tsx
  test/components/views/rooms/RoomPreviewCard-test.tsx
Labels: T-Enhancement

#101 Fix label sync
  .github/labels.yml
Labels: T-Task

#100 Remove right panel toggling behaviour on room header buttons
  playwright/e2e/read-receipts/index.ts
  src/components/views/rooms/RoomHeader.tsx
  src/components/views/rooms/RoomHeader/VideoRoomChatButton.tsx
  src/stores/right-panel/RightPanelStore.ts
  test/components/views/rooms/RoomHeader/VideoRoomChatButton-test.tsx
  test/stores/right-panel/RightPanelStore-test.ts
Labels: T-Enhancement

#104 Roll back change to device isolation mode
  src/settings/controllers/DeviceIsolationModeController.ts
  test/settings/controllers/DeviceIsolationModeController-test.ts
Labels: T-Enhancement
