Repository element-hq/matrix-react-sdk, pull requests merged in 2024-10, with the labels that each got.

#90 Fix untranslated keys being rendered in `/help` dialog
  src/components/views/dialogs/SlashCommandHelpDialog.tsx
Labels: T-Defect

#98 Allow to unpin redacted event
  src/utils/PinningUtils.ts
  test/utils/PinningUtils-test.ts
Labels: T-Defect

#108 Use Compound close icon in favour of mishmash of x/close icons
  res/css/components/views/beacon/_DialogSidebar.pcss
  res/css/structures/_SearchBox.pcss
  res/css/structures/_UploadBar.pcss
  res/css/structures/_UserMenu.pcss
  res/css/views/dialogs/_PollCreateDialog.pcss
  res/css/views/dialogs/security/_AccessSecretStorageDialog.pcss
  res/css/views/elements/_AccessibleButton.pcss
  res/css/views/elements/_ImageView.pcss
  res/css/views/elements/_Validation.pcss
  res/img/compound/close-16px.svg
  res/img/compound/close-8px.svg
  res/img/element-icons/x-8px.svg
  res/img/feather-customised/x.svg
  res/img/icons-close.svg
  res/img/image-view/close.svg
  src/components/views/beacon/DialogSidebar.tsx
  src/components/views/beacon/RoomLiveShareWarning.tsx
  src/components/views/rooms/RoomKnocksBar.tsx
  src/components/views/settings/tabs/room/PeopleRoomSettingsTab.tsx
  src/voice-broadcast/components/atoms/VoiceBroadcastHeader.tsx
  src/voice-broadcast/components/molecules/VoiceBroadcastSmallPlaybackBody.tsx
  test/components/views/beacon/__snapshots__/DialogSidebar-test.tsx.snap
  test/components/views/beacon/__snapshots__/RoomLiveShareWarning-test.tsx.snap
  test/components/views/settings/tabs/room/__snapshots__/PeopleRoomSettingsTab-test.tsx.snap
  test/voice-broadcast/components/molecules/__snapshots__/VoiceBroadcastPreRecordingPip-test.tsx.snap
  test/voice-broadcast/components/molecules/__snapshots__/VoiceBroadcastSmallPlaybackBody-test.tsx.snap
Labels: T-Enhancement

#107 Remove unused icon files
  res/img/e2e/disabled.svg
  res/img/element-icons/Record.svg
  res/img/element-icons/Stop.svg
  res/img/element-icons/brands/element.svg
  res/img/element-icons/devices.svg
  res/img/element-icons/qrcode.svg
Labels: T-Task

#109 Ensure no race condition between page load and waitForRequest set up
  playwright/e2e/oidc/oidc-native.spec.ts
Labels: T-Task

#112 Respect `io.element.jitsi` `useFor1To1Calls` in well-known
  src/LegacyCallHandler.tsx
  src/widgets/Jitsi.ts
Labels: T-Enhancement

#105 Remove legacy room header and promote beta room header
  res/css/_components.pcss
  res/css/components/views/beacon/_RoomLiveShareWarning.pcss
  src/components/structures/RoomView.tsx
  src/components/structures/WaitingForThirdPartyRoomView.tsx
  src/components/views/beacon/RoomLiveShareWarning.tsx
  src/components/views/context_menus/RoomContextMenu.tsx
  src/components/views/right_panel/LegacyRoomHeaderButtons.tsx
  src/components/views/rooms/LegacyRoomHeader.tsx
  src/hooks/useCall.ts
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
  test/components/structures/__snapshots__/RoomView-test.tsx.snap
  test/components/views/beacon/RoomLiveShareWarning-test.tsx
  test/components/views/beacon/__snapshots__/RoomLiveShareWarning-test.tsx.snap
  test/components/views/context_menus/RoomContextMenu-test.tsx
  test/components/views/right_panel/LegacyRoomHeaderButtons-test.tsx
  test/components/views/right_panel/__snapshots__/LegacyRoomHeaderButtons-test.tsx.snap
  test/components/views/rooms/LegacyRoomHeader-test.tsx
  test/components/views/settings/tabs/user/__snapshots__/LabsUserSettingsTab-test.tsx.snap
Labels: T-Enhancement

#111 Disable ICE fallback based on well-known configuration
  src/LegacyCallHandler.tsx
  src/components/views/settings/tabs/user/VoiceUserSettingsTab.tsx
  src/settings/Settings.tsx
  src/settings/controllers/FallbackIceServerController.ts
  src/settings/controllers/MatrixClientBackedController.ts
  src/settings/controllers/ServerSupportUnstableFeatureController.ts
  test/settings/controllers/FallbackIceServerController-test.ts
Labels: T-Enhancement

#119 Update emoji text, border and background colour in timeline
  res/css/views/messages/_ReactionsRow.pcss
  res/css/views/messages/_ReactionsRowButton.pcss
Labels: T-Enhancement

#44 Force verification even for refreshed clients
  package.json
  playwright/e2e/login/login.spec.ts
  src/Lifecycle.ts
  src/SdkConfig.ts
  src/components/structures/MatrixChat.tsx
  src/components/structures/auth/CompleteSecurity.tsx
  src/components/views/auth/Welcome.tsx
  src/hooks/useUserOnboardingContext.ts
  test/components/structures/MatrixChat-test.tsx
  test/components/structures/__snapshots__/MatrixChat-test.tsx.snap
  yarn.lock
Labels: T-Enhancement

#99 Ditch right panel tabs and re-add close button
  playwright/e2e/crypto/crypto.spec.ts
  playwright/e2e/crypto/dehydration.spec.ts
  playwright/e2e/crypto/utils.ts
  playwright/e2e/integration-manager/utils.ts
  playwright/e2e/lazy-loading/lazy-loading.spec.ts
  playwright/e2e/read-receipts/index.ts
  playwright/e2e/right-panel/right-panel.spec.ts
  playwright/e2e/spaces/threads-activity-centre/index.ts
  playwright/e2e/spaces/threads-activity-centre/threadsActivityCentre.spec.ts
  playwright/snapshots/crypto/crypto.spec.ts/RoomSummaryCard-with-verified-e2ee-linux.png
  playwright/snapshots/pinned-messages/pinned-messages.spec.ts/pinned-messages-list-empty-linux.png
  playwright/snapshots/right-panel/file-panel.spec.ts/empty-linux.png
  playwright/snapshots/right-panel/notification-panel.spec.ts/empty-linux.png
  playwright/snapshots/right-panel/right-panel.spec.ts/with-name-and-address-linux.png
  playwright/snapshots/user-view/user-view.spec.ts/user-info-linux.png
  res/css/_components.pcss
  res/css/views/right_panel/_ExtensionsCard.pcss
  res/css/views/right_panel/_RightPanelTabs.pcss
  res/css/views/right_panel/_RoomSummaryCard.pcss
  res/css/views/rooms/_MemberList.pcss
  src/components/structures/FilePanel.tsx
  src/components/structures/NotificationPanel.tsx
  src/components/structures/RightPanel.tsx
  src/components/structures/ThreadPanel.tsx
  src/components/views/right_panel/BaseCard.tsx
  src/components/views/right_panel/ExtensionsCard.tsx
  src/components/views/right_panel/PinnedMessagesCard.tsx
  src/components/views/right_panel/RightPanelTabs.tsx
  src/components/views/right_panel/RoomSummaryCard.tsx
  src/components/views/right_panel/TimelineCard.tsx
  src/components/views/rooms/MemberList.tsx
  src/components/views/rooms/ThirdPartyMemberInfo.tsx
  src/i18n/strings/en_EN.json
  test/components/structures/__snapshots__/FilePanel-test.tsx.snap
  test/components/views/right_panel/BaseCard-test.tsx
  test/components/views/right_panel/RightPanelTabs-test.tsx
  test/components/views/right_panel/RoomSummaryCard-test.tsx
  test/components/views/right_panel/__snapshots__/BaseCard-test.tsx.snap
  test/components/views/right_panel/__snapshots__/ExtensionsCard-test.tsx.snap
  test/components/views/right_panel/__snapshots__/PinnedMessagesCard-test.tsx.snap
  test/components/views/right_panel/__snapshots__/RightPanelTabs-test.tsx.snap
  test/components/views/right_panel/__snapshots__/RoomSummaryCard-test.tsx.snap
  test/components/views/right_panel/__snapshots__/UserInfo-test.tsx.snap
  test/components/views/rooms/__snapshots__/ThirdPartyMemberInfo-test.tsx.snap
Labels: T-Enhancement

#118 Add a pinned message badge under a pinned message
  playwright/e2e/pinned-messages/index.ts
  playwright/e2e/pinned-messages/pinned-messages.spec.ts
  playwright/snapshots/pinned-messages/pinned-messages.spec.ts/pinned-message-Msg1-linux.png
  res/css/_components.pcss
  res/css/views/messages/_PinnedMessageBadge.pcss
  res/css/views/messages/_ReactionsRow.pcss
  res/css/views/rooms/_EventBubbleTile.pcss
  res/css/views/rooms/_EventTile.pcss
  src/components/views/messages/PinnedMessageBadge.tsx
  src/components/views/rooms/EventTile.tsx
  src/i18n/strings/en_EN.json
  test/components/views/messages/PinnedMessageBadge-test.tsx
  test/components/views/messages/__snapshots__/PinnedMessageBadge-test.tsx.snap
  test/components/views/rooms/EventTile-test.tsx
Labels: T-Enhancement

#110 Tweak default right panel size to be 320px except for maximised widgets at 420px
  package.json
  playwright/snapshots/crypto/crypto.spec.ts/RoomSummaryCard-with-verified-e2ee-linux.png
  playwright/snapshots/pinned-messages/pinned-messages.spec.ts/pinned-messages-list-empty-linux.png
  playwright/snapshots/polls/polls.spec.ts/ThreadView-with-a-poll-on-bubble-layout-linux.png
  playwright/snapshots/polls/polls.spec.ts/ThreadView-with-a-poll-on-group-layout-linux.png
  playwright/snapshots/right-panel/file-panel.spec.ts/empty-linux.png
  playwright/snapshots/right-panel/file-panel.spec.ts/file-tiles-list-linux.png
  playwright/snapshots/right-panel/notification-panel.spec.ts/empty-linux.png
  playwright/snapshots/right-panel/right-panel.spec.ts/with-name-and-address-linux.png
  playwright/snapshots/threads/threads.spec.ts/Reply-to-the-location-on-ThreadView-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/highlighted-search-results-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/search-aux-panel-linux.png
  playwright/snapshots/timeline/timeline.spec.ts/search-results-with-TextualEvent-linux.png
  playwright/snapshots/user-view/user-view.spec.ts/user-info-linux.png
  src/components/structures/MainSplit.tsx
  src/components/structures/RoomView.tsx
  src/components/structures/SpaceRoomView.tsx
  src/components/structures/UserView.tsx
  src/contexts/RoomContext.ts
  test/components/structures/MainSplit-test.tsx
  test/components/structures/RoomView-test.tsx
  test/components/structures/__snapshots__/MainSplit-test.tsx.snap
  test/components/structures/__snapshots__/RoomView-test.tsx.snap
  test/components/views/rooms/SendMessageComposer-test.tsx
  test/test-utils/room.ts
  yarn.lock
Labels: T-Enhancement

#122 Prefer wrapped Compound React icon assets
  .eslintrc.js
  src/components/structures/RoomStatusBar.tsx
  src/components/views/auth/LoginWithQRFlow.tsx
  src/components/views/messages/MessageActionBar.tsx
  src/components/views/messages/PinnedMessageBadge.tsx
  src/components/views/right_panel/BaseCard.tsx
  src/components/views/right_panel/ExtensionsCard.tsx
  src/components/views/right_panel/RoomSummaryCard.tsx
  src/components/views/right_panel/UserInfo.tsx
  src/components/views/rooms/MemberList.tsx
  src/components/views/rooms/PinnedEventTile.tsx
  src/components/views/rooms/PinnedMessageBanner.tsx
  src/components/views/rooms/RoomHeader.tsx
  src/components/views/rooms/RoomHeader/VideoRoomChatButton.tsx
  src/components/views/rooms/ThreadSummary.tsx
  src/components/views/settings/UserProfileSettings.tsx
  src/components/views/settings/devices/LoginWithQRSection.tsx
  src/components/views/settings/tabs/user/SidebarUserSettingsTab.tsx
  src/components/views/spaces/threads-activity-centre/ThreadsActivityCentreButton.tsx
  src/toasts/IncomingCallToast.tsx
  test/components/structures/__snapshots__/RoomView-test.tsx.snap
  test/components/views/messages/__snapshots__/PinnedMessageBadge-test.tsx.snap
  test/components/views/right_panel/__snapshots__/ExtensionsCard-test.tsx.snap
  test/components/views/right_panel/__snapshots__/PinnedMessagesCard-test.tsx.snap
  test/components/views/right_panel/__snapshots__/RoomSummaryCard-test.tsx.snap
  test/components/views/rooms/RoomHeader/__snapshots__/VideoRoomChatButton-test.tsx.snap
  test/components/views/rooms/__snapshots__/PinnedEventTile-test.tsx.snap
  test/components/views/rooms/__snapshots__/PinnedMessageBanner-test.tsx.snap
  test/components/views/rooms/__snapshots__/RoomHeader-test.tsx.snap
  test/components/views/settings/devices/__snapshots__/LoginWithQRFlow-test.tsx.snap
  test/components/views/settings/devices/__snapshots__/LoginWithQRSection-test.tsx.snap
  test/components/views/settings/tabs/user/__snapshots__/SidebarUserSettingsTab-test.tsx.snap
  test/components/views/spaces/__snapshots__/SpacePanel-test.tsx.snap
  test/components/views/spaces/__snapshots__/ThreadsActivityCentre-test.tsx.snap
Labels: T-Task

#123 Replace composer icons with Compound variants
  playwright/snapshots/permalinks/permalinks.spec.ts/permalink-rendering-linux.png
  res/css/views/context_menus/_MessageContextMenu.pcss
  res/css/views/rooms/_MessageComposer.pcss
  res/css/views/rooms/_MessageComposerFormatBar.pcss
  res/img/element-icons/room/composer/bold.svg
  res/img/element-icons/room/composer/bulleted_list.svg
  res/img/element-icons/room/composer/code_block.svg
  res/img/element-icons/room/composer/indent_decrease.svg
  res/img/element-icons/room/composer/indent_increase.svg
  res/img/element-icons/room/composer/inline_code.svg
  res/img/element-icons/room/composer/italic.svg
  res/img/element-icons/room/composer/link.svg
  res/img/element-icons/room/composer/location.svg
  res/img/element-icons/room/composer/numbered_list.svg
  res/img/element-icons/room/composer/quote.svg
  res/img/element-icons/room/composer/rich_text.svg
  res/img/element-icons/room/composer/strikethrough.svg
  res/img/element-icons/room/composer/underline.svg
  res/img/element-icons/room/format-bar/bold.svg
  res/img/element-icons/room/format-bar/code.svg
  res/img/element-icons/room/format-bar/italic.svg
  res/img/element-icons/room/format-bar/quote.svg
  res/img/element-icons/room/format-bar/strikethrough.svg
  src/components/views/elements/Pill.tsx
  src/components/views/rooms/wysiwyg_composer/components/FormattingButtons.tsx
  test/components/views/messages/TextualBody-test.tsx
  test/components/views/messages/__snapshots__/TextualBody-test.tsx.snap
  test/components/views/rooms/wysiwyg_composer/components/__snapshots__/FormattingButtons-test.tsx.snap
Labels: T-Enhancement

#43 Add support for rendering media captions
  src/components/views/messages/MessageEvent.tsx
  src/components/views/messages/TextualBody.tsx
  src/utils/FileUtils.ts
  test/components/views/messages/MessageEvent-test.tsx
Labels: Z-Community-PR, T-Enhancement

#125 Update to @vector-im/matrix-wysiwyg
  package.json
  src/components/views/rooms/wysiwyg_composer/DynamicImportWysiwygComposer.tsx
  src/components/views/rooms/wysiwyg_composer/components/FormattingButtons.tsx
  src/components/views/rooms/wysiwyg_composer/components/LinkModal.tsx
  src/components/views/rooms/wysiwyg_composer/components/WysiwygAutocomplete.tsx
  src/components/views/rooms/wysiwyg_composer/components/WysiwygComposer.tsx
  src/components/views/rooms/wysiwyg_composer/hooks/useInputEventProcessor.ts
  src/components/views/rooms/wysiwyg_composer/hooks/usePlainTextListeners.ts
  src/components/views/rooms/wysiwyg_composer/hooks/useSuggestion.ts
  src/components/views/rooms/wysiwyg_composer/hooks/utils.ts
  src/components/views/rooms/wysiwyg_composer/utils/autocomplete.ts
  src/components/views/rooms/wysiwyg_composer/utils/createMessageContent.ts
  test/components/views/rooms/wysiwyg_composer/components/FormattingButtons-test.tsx
  test/components/views/rooms/wysiwyg_composer/components/LinkModal-test.tsx
  yarn.lock
Labels: T-Task

#126 Remove usage of deprecated `CryptoEvent`s
  src/DeviceListener.ts
  src/components/structures/MatrixChat.tsx
  src/components/structures/RoomView.tsx
  src/components/views/dialogs/KeySignatureUploadFailedDialog.tsx
  src/components/views/right_panel/UserInfo.tsx
  src/components/views/rooms/EventTile.tsx
  src/components/views/rooms/MemberTile.tsx
  src/i18n/strings/en_EN.json
Labels: T-Task

#124 Refactor stores and their relationship to the MatrixClientPeg
  src/MatrixClientPeg.ts
  src/stores/AsyncStoreWithClient.ts
  src/stores/AutoRageshakeStore.ts
  src/stores/BreadcrumbsStore.ts
  src/stores/CallStore.ts
  src/stores/ModalWidgetStore.ts
  src/stores/OwnBeaconStore.ts
  src/stores/OwnProfileStore.ts
  src/stores/ReadyWatchingStore.ts
  src/stores/VoiceRecordingStore.ts
  src/stores/WidgetStore.ts
  src/stores/local-echo/EchoStore.ts
  src/stores/notifications/RoomNotificationStateStore.ts
  src/stores/right-panel/RightPanelStore.ts
  src/stores/room-list/MessagePreviewStore.ts
  src/stores/room-list/RoomListLayoutStore.ts
  src/stores/room-list/RoomListStore.ts
  src/stores/spaces/SpaceStore.ts
  src/stores/widgets/WidgetLayoutStore.ts
  src/stores/widgets/WidgetMessagingStore.ts
  test/stores/AutoRageshakeStore-test.ts
  test/stores/OwnProfileStore-test.ts
  test/stores/SpaceStore-test.ts
  test/stores/VoiceRecordingStore-test.ts
  test/stores/WidgetLayoutStore-test.ts
  test/stores/room-list/MessagePreviewStore-test.ts
  test/stores/room-list/RoomListStore-test.ts
  test/stores/room-list/SlidingRoomListStore-test.ts
Labels: T-Task

#133 Improve logging in SessionLock
  src/utils/SessionLock.ts
Labels: T-Task

#137 Fix vertical overflow on the mobile register screen
  res/css/structures/auth/_MobileRegistration.pcss
Labels: T-Defect

#135 Fix bell icons on room list hover being black squares
  src/stores/ReadyWatchingStore.ts
  test/MatrixClientPeg-test.ts
  test/test-utils/test-utils.ts
Labels: T-Defect

#136 Add aria-label to e2e icon
  src/components/views/rooms/EventTile.tsx
  src/i18n/strings/en_EN.json
Labels: T-Defect

#139 Revert #124 and #135
  src/MatrixClientPeg.ts
  src/stores/AsyncStoreWithClient.ts
  src/stores/AutoRageshakeStore.ts
  src/stores/BreadcrumbsStore.ts
  src/stores/CallStore.ts
  src/stores/ModalWidgetStore.ts
  src/stores/OwnBeaconStore.ts
  src/stores/OwnProfileStore.ts
  src/stores/ReadyWatchingStore.ts
  src/stores/VoiceRecordingStore.ts
  src/stores/WidgetStore.ts
  src/stores/local-echo/EchoStore.ts
  src/stores/notifications/RoomNotificationStateStore.ts
  src/stores/right-panel/RightPanelStore.ts
  src/stores/room-list/MessagePreviewStore.ts
  src/stores/room-list/RoomListLayoutStore.ts
  src/stores/room-list/RoomListStore.ts
  src/stores/spaces/SpaceStore.ts
  src/stores/widgets/WidgetLayoutStore.ts
  src/stores/widgets/WidgetMessagingStore.ts
  test/MatrixClientPeg-test.ts
  test/stores/AutoRageshakeStore-test.ts
  test/stores/OwnProfileStore-test.ts
  test/stores/SpaceStore-test.ts
  test/stores/VoiceRecordingStore-test.ts
  test/stores/WidgetLayoutStore-test.ts
  test/stores/room-list/MessagePreviewStore-test.ts
  test/stores/room-list/RoomListStore-test.ts
  test/stores/room-list/SlidingRoomListStore-test.ts
  test/test-utils/test-utils.ts
Labels: T-Defect

#127 Upgrade emojibase-bindings and remove local handling of emoticon variations
  package.json
  src/components/views/rooms/BasicMessageComposer.tsx
  src/components/views/rooms/wysiwyg_composer/hooks/useSuggestion.ts
  test/components/views/rooms/BasicMessageComposer-test.tsx
  test/components/views/rooms/wysiwyg_composer/components/WysiwygComposer-test.tsx
  yarn.lock
Labels: T-Enhancement

#143 Fix flaky crypto playwright tests
  playwright/e2e/crypto/crypto.spec.ts
  playwright/e2e/crypto/event-shields.spec.ts
  playwright/e2e/utils.ts
  playwright/pages/client.ts
Labels: T-Task

#145 Pin to Ubuntu 22
  .github/workflows/backport.yml
  .github/workflows/end-to-end-tests-netlify.yaml
  .github/workflows/end-to-end-tests.yaml
  .github/workflows/netlify.yaml
  .github/workflows/notify-element-web.yml
  .github/workflows/playwright-image-updates.yaml
  .github/workflows/pull_request_base_branch.yaml
  .github/workflows/static_analysis.yaml
  .github/workflows/tests.yml
Labels: T-Task

#142 Replace `MatrixClient.checkSecretStorageKey` by `MatrixClient.SecretStorage.checkKey`
  src/SecurityManager.ts
  src/components/views/dialogs/security/AccessSecretStorageDialog.tsx
  test/components/views/dialogs/AccessSecretStorageDialog-test.tsx
  test/test-utils/test-utils.ts
Labels: T-Task

#138 Remove feature_dehydration
  playwright/e2e/login/soft_logout.spec.ts
  src/Lifecycle.ts
  src/SecurityManager.ts
  src/components/structures/auth/SoftLogout.tsx
  src/i18n/strings/en_EN.json
  src/settings/Settings.tsx
Labels: T-Enhancement

#150 Deduplicate icons using Compound Design Tokens
  playwright/snapshots/forgot-password/forgot-password.spec.ts/forgot-password-linux.png
  res/css/structures/_AutocompleteInput.pcss
  res/css/structures/_RoomSearch.pcss
  res/css/views/auth/_AuthBody.pcss
  res/css/views/dialogs/_InviteDialog.pcss
  res/img/compound/checkbox-32px.svg
  res/img/compound/error-16px.svg
  res/img/compound/padlock-32px.svg
  res/img/element-icons/Email-icon.svg
  res/img/element-icons/roomlist/search.svg
  res/img/feather-customised/help-circle.svg
  res/img/icon-pill-remove.svg
  res/img/plus.svg
  src/components/structures/AutocompleteInput.tsx
  src/components/structures/ErrorMessage.tsx
  src/components/structures/auth/ForgotPassword.tsx
  src/components/structures/auth/forgot-password/EnterEmail.tsx
  src/components/views/dialogs/InviteDialog.tsx
  src/components/views/elements/AppPermission.tsx
  src/components/views/messages/DecryptionFailureBody.tsx
  src/components/views/rooms/EntityTile.tsx
  src/voice-broadcast/components/atoms/VoiceBroadcastError.tsx
  src/voice-broadcast/components/atoms/VoiceBroadcastRecordingConnectionError.tsx
  test/components/views/elements/__snapshots__/AppTile-test.tsx.snap
  test/components/views/messages/__snapshots__/DecryptionFailureBody-test.tsx.snap
  test/voice-broadcast/components/molecules/__snapshots__/VoiceBroadcastPlaybackBody-test.tsx.snap
Labels: T-Task

#144 Update design of files list in right panel
  playwright/e2e/right-panel/file-panel.spec.ts
  playwright/snapshots/audio-player/audio-player.spec.ts/Selected-EventTile-of-audio-player-with-a-reply-bubble-layout-linux.png
  playwright/snapshots/audio-player/audio-player.spec.ts/Selected-EventTile-of-audio-player-with-a-reply-chain-bubble-layout-linux.png
  playwright/snapshots/audio-player/audio-player.spec.ts/Selected-EventTile-of-audio-player-with-a-reply-chain-group-layout-linux.png
  playwright/snapshots/audio-player/audio-player.spec.ts/Selected-EventTile-of-audio-player-with-a-reply-chain-irc-layout-linux.png
  playwright/snapshots/audio-player/audio-player.spec.ts/Selected-EventTile-of-audio-player-with-a-reply-group-layout-linux.png
  playwright/snapshots/audio-player/audio-player.spec.ts/Selected-EventTile-of-audio-player-with-a-reply-irc-layout-linux.png
  playwright/snapshots/right-panel/file-panel.spec.ts/file-tiles-list-linux.png
  res/css/structures/_FilePanel.pcss
  res/css/views/messages/_MFileBody.pcss
  src/components/structures/MessagePanel.tsx
  src/components/views/messages/MFileBody.tsx
  src/components/views/rooms/EventTile.tsx
  src/i18n/strings/en_EN.json
  src/usercontent/index.ts
  src/utils/FileUtils.ts
  test/components/views/messages/MFileBody-test.tsx
  test/components/views/messages/__snapshots__/MFileBody-test.tsx.snap
  test/components/views/rooms/EventTile-test.tsx
  test/utils/FileUtils-test.ts
Labels: T-Enhancement

#148 Replace `MatrixClient.userHasCrossSigningKeys` by `MatrixClient.getCrypto.userHasCrossSigningKeys`
  src/components/structures/MatrixChat.tsx
  test/components/structures/MatrixChat-test.tsx
Labels: T-Task

#146 Replace `MatrixClient.prepareToEncrypt` by `MatrixClient.getCrypto.prepareToEncrypt`
  src/LegacyCallHandler.tsx
  src/components/views/rooms/SendMessageComposer.tsx
  test/LegacyCallHandler-test.ts
  test/components/views/rooms/SendMessageComposer-test.tsx
  test/test-utils/test-utils.ts
Labels: T-Task

#151 Update to Compound v7
  package.json
  playwright/e2e/crypto/crypto.spec.ts
  src/components/views/right_panel/RoomSummaryCard.tsx
  test/components/views/right_panel/__snapshots__/RoomSummaryCard-test.tsx.snap
  yarn.lock
Labels: T-Task

#147 Always show link new device flow even if unsupported
  playwright/snapshots/user-menu/user-menu.spec.ts/user-menu-linux.png
  res/css/views/auth/_LoginWithQR.pcss
  src/components/structures/UserMenu.tsx
  src/components/views/auth/LoginWithQRFlow.tsx
  src/components/views/settings/devices/LoginWithQRSection.tsx
  src/i18n/strings/en_EN.json
  test/components/views/settings/devices/LoginWithQRSection-test.tsx
  test/components/views/settings/devices/__snapshots__/LoginWithQRFlow-test.tsx.snap
  test/components/views/settings/devices/__snapshots__/LoginWithQRSection-test.tsx.snap
Labels: T-Enhancement, X-Upcoming-Release-Blocker

#35 Remove redundant yarn.lock entry for widget-api
  yarn.lock
Labels: T-Task

#140 Replace `MatrixClient.isCryptoEnabled` by `MatrixClient.getCrypto`
  src/components/structures/MatrixChat.tsx
  src/components/structures/RoomView.tsx
  src/components/views/rooms/SendMessageComposer.tsx
  src/hooks/useEncryptionStatus.ts
  test/components/structures/MatrixChat-test.tsx
  test/components/structures/RoomView-test.tsx
  test/components/views/dialogs/security/CreateSecretStorageDialog-test.tsx
  test/components/views/right_panel/UserInfo-test.tsx
  test/components/views/rooms/RoomHeader-test.tsx
  test/components/views/rooms/SendMessageComposer-test.tsx
  test/components/views/settings/devices/LoginWithQR-test.tsx
  test/components/views/settings/devices/LoginWithQRSection-test.tsx
  test/test-utils/client.ts
  test/test-utils/test-utils.ts
Labels: T-Task

#128 Use new `CryptoEvent` import
  playwright/e2e/crypto/utils.ts
  src/DecryptionFailureTracker.ts
  src/DeviceListener.ts
  src/async-components/views/dialogs/security/CreateSecretStorageDialog.tsx
  src/components/structures/MatrixChat.tsx
  src/components/structures/MatrixClientContextProvider.tsx
  src/components/structures/RoomView.tsx
  src/components/structures/auth/LoginSplashView.tsx
  src/components/views/dialogs/devtools/VerificationExplorer.tsx
  src/components/views/right_panel/UserInfo.tsx
  src/components/views/rooms/EventTile.tsx
  src/components/views/rooms/MemberTile.tsx
  src/components/views/settings/CrossSigningPanel.tsx
  src/components/views/settings/SecureBackupPanel.tsx
  src/components/views/settings/devices/useOwnDevices.ts
  src/stores/SetupEncryptionStore.ts
  src/stores/right-panel/RightPanelStore.ts
  test/DecryptionFailureTracker-test.ts
  test/DeviceListener-test.ts
  test/components/structures/MatrixClientContextProvider-test.tsx
  test/components/structures/auth/LoginSplashView-test.tsx
Labels: T-Task
